#-----------------------------------------
# CloudBuild Pipeline for Staging CloudRun
#-----------------------------------------
steps:
# Docker Build Image
  - name: gcr.io/cloud-builders/docker
    id  : BUILD
    args: ['build', '-t', '$_SERVICE_IMAGE', '.', '-f', 'Dockerfile']

# Docker Push Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id  : PUSH
    args: ['push', '$_SERVICE_IMAGE']

# Docker Deploy image to Cloud Run
  - name: gcr.io/cloud-builders/gcloud
    id  : DEPLOY
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --project=$_SERVICE_PROJECT
      - --region=$_SERVICE_REGION
      - --image=$_SERVICE_IMAGE

images: # Display the image in the build results - Build Artifacts
- $_SERVICE_IMAGE

substitutions:
    _SERVICE_IMAGE    : us-west2-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY}/${_DOCKER_IMAGENAME}:${SHORT_SHA}
    _SERVICE_REGION   : us-west2
    _SERVICE_PROJECT  : staging-443611
    _SERVICE_NAME     : my-docker-staging
    _DOCKER_REGISTRY  : falinski-docker-repo
    _DOCKER_IMAGENAME : myapp-staging

options:
  logging: CLOUD_LOGGING_ONLY
